"""LLM prompt templates."""

from app.prompts.extraction import EXTRACTION_SYSTEM, EXTRACTION_USER_TEMPLATE
from app.prompts.canonicalization import CANONICAL_FAQ_SYSTEM, CANONICAL_FAQ_USER_TEMPLATE
from app.prompts.memory_graph import RELATION_INFERENCE_SYSTEM, RELATION_INFERENCE_USER_TEMPLATE

__all__ = [
    "EXTRACTION_SYSTEM",
    "EXTRACTION_USER_TEMPLATE",
    "CANONICAL_FAQ_SYSTEM",
    "CANONICAL_FAQ_USER_TEMPLATE",
    "RELATION_INFERENCE_SYSTEM",
    "RELATION_INFERENCE_USER_TEMPLATE",
]
